spring:
  application:
    name: backend

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: quiz-group

  data:
    redis:
      host: localhost
      port: 6379

  graphql:
    http:
      path: /graphql

    websocket:
      path: /graphql

    cors:
      allowed-origins: "http://localhost:4200"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
