spring:
  application:
    name: live-quizzer

  main:
    web-application-type: reactive

  graphql:
    http:
      path: /graphql
    websocket:
      path: /graphql

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: quiz-group

  data:
    redis:
      host: localhost
      port: 6379
